version: "3.8"
services:
  redis:
    image: redis:6.0.9
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=queue
  counter:
    build: .
    command: ./entrypoint.sh
    ports:
      - "5000:5000"
    depends_on:
      - celery
  celery:
    build: .
    command: ./entrypoint_c.sh
    depends_on:
      - redis
      - postgres
